export { analyzeProject, analyzeFile, RULE_WEIGHTS } from './analyzer.js'
export { buildReport, formatMarkdown } from './reporter.js'
export { computeDiff } from './diff.js'
export type { DriftReport, FileReport, DriftIssue, DriftDiff, FileDiff, DriftConfig } from './types.js'
export { loadHistory, saveSnapshot } from './snapshot.js'
export type { SnapshotEntry, SnapshotHistory } from './snapshot.js'
